mlflow_uri: "http://localhost:2345/"
mlflow_experiment_name: "overfit"

lizard_dir: "C:/Users/abdul/Desktop/TUM/thesis/lizard"
device_id: 0
tile_size: 128

train_batch_size: 64
val_batch_size: 512
num_iters: 500
validate_every: 10
learning_rate: 0.001
